### ISSUE TITLE
[iOS Bootcamp] Pre-work: Tip Calculator App - Review my app

### ISSUE THREAD

**Issue by Monte9** [Monte9/typps#1]
My app is complete, please review /cc @codepath @codepathreview

Hoping to receive constructive feedback on how I can improve the app. Also, feel free to point out bad practices that I might have adopted in this project.

Thanks in advance.

**Comment by codepathreview** [comment]
Great work!! This exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer learn the practical elements of iOS development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Great to see you were able to complete a large number of optional features to your app already. Your project looks great. As you can probably tell, the optional features available on each project are a great vehicle for exploring the iOS framework deeper.

We'll be following up with you again shortly to outline the next steps in the admissions process.
